### ISSUE TITLE
How to add more languages?

### ISSUE THREAD

**Issue by marcofranssen** [FormidableLabs/prism-react-renderer#102]
I'm looking how to add a few more languages to be supported.

From this list it seems prism support a whole lot more languages.

https://prismjs.com/#supported-languages

How can I configure the React component to support additional languages like `nginx` and `ini` files?

**Comment by kitten** [comment]
Please check the FAQ, it's described in the first item ✌️ https://github.com/FormidableLabs/prism-react-renderer#faq

**Comment by max-programming** [comment]
> Please check the FAQ, it's described in the first item ✌️ https://github.com/FormidableLabs/prism-react-renderer#faq
> 
> You can also replace the default subset of the Prism library with your own installation entirely

But I have a Next.js TS project and I don't really get how to use it. I can't use `require`

**Comment by max-programming** [comment]
![image](https://user-images.githubusercontent.com/51731966/126071072-e662736e-89c4-4a59-b8ea-13895af81132.png)
I found out a way but it still gives an error even thought I installed the types.

![image](https://user-images.githubusercontent.com/51731966/126071119-d32cf6ea-2f2b-4784-af6b-ec75534e65be.png)
Also this is what I get
