### ISSUE TITLE
Feature: github dark theme

### ISSUE THREAD

**Issue by armano2** [FormidableLabs/prism-react-renderer#110]
Github dark theme is not present in theme list.

**Comment by kitten** [comment]
Hiya 👋

Sorry, but for this repo I haven't really accepted theme requests. There's a tool to convert themes and it's relatively easy port existing Prism themes or to create ones from scratch. This means that mostly I've been accepting and reviewing theme contributions in the form of PRs.

However, for issues for themes they're just too likely to stick around permanently or indefinitely 😅 so I'll close this for now, but if you'd like to contribute a theme and open a PR let me know.

**Comment by armano2** [comment]
ok fair enough, I'm going to prepare PR than ;)
