### ISSUE TITLE
Broken Github theme

### ISSUE THREAD

**Issue by Andrew-web-coder** [FormidableLabs/prism-react-renderer#115]
Github theme is broken in v1.2.0

You can easily see that here - https://codesandbox.io/s/prism-react-renderer-example-forked-ws3pz?file=/src/Basic.js

And it works fine after changing to older versions.

**Comment by kitten** [comment]
I've reverted PR #100 that changed the styles for now until I can check which changes from it are save to pick over: https://github.com/FormidableLabs/prism-react-renderer/commit/0040cd472d20cb8863a1740ee88fd276e8497601

**Comment by Andrew-web-coder** [comment]
But you did not release v.1.2.1 therefore it is still broken in npm

**Comment by kitten** [comment]
@Andrew-web-coder Nope, it's been definitely released on the day https://www.npmjs.com/package/prism-react-renderer/v/1.2.1

**Comment by Andrew-web-coder** [comment]
Hmm, true, then I just do not understand why GitHub shows 1.2.0 as the `Latest release` - https://github.com/FormidableLabs/prism-react-renderer/releases
