### ISSUE TITLE
Typescript typings issues with Prism imported manually (from PrismJS)?

### ISSUE THREAD

**Issue by soykje** [FormidableLabs/prism-react-renderer#116]
Hi there! :wave:

I have a working setup with `prism-react-renderer`, using a manual import of Prism library and a dedicated [Babel plugin](https://www.npmjs.com/package/babel-plugin-prismjs) that allows me to configure my Prism instance languages in a way I found more convenient to me, than the FAQ proposal.

Recently I decided to start converting my code to Typescript, so I had to install Prism types from DefinitelyTyped (to make my custom import working on build).

This brought me to an unexpected issue, with typing differences between those from DT and from `prism-react-renderer` :disappointed: 

I first tried to "merge" both types using a custom declaration file, to reexport `PrismLib` type then, but this appeared to be quite an heavy task to me, so I finally ended up with this workaround:

```tsx
import Prism from 'prismjs' // Correctly typed after a "@types/prismjs" install
import Highlight, { Prism as PrismRR, Language } from 'prism-react-renderer'
import palenight from 'prism-react-renderer/themes/palenight'

import { Pre, Line, LineNo, LineContent } from './styles'

interface CodeBlockProps {
  value: string
  language?: Language
}

type PrismLib = typeof PrismRR & typeof Prism // 

const CodeBlock = ({
  value,
  language = 'bash'
}: CodeBlockProps): JSX.Element => (
  <Highlight Prism={Prism as PrismLib} theme={palenight} code={value} language={language}>
    {({
      className,
      style,
      tokens,
      getLineProps,
      getTokenProps
    }) => (
      <Pre className={className} style={style}>
        {tokens.map((line, i) => (
          <Line key={`${line}`} {...getLineProps({ line, key: i })}>
            <LineNo>{i + 1}</LineNo>
            <LineContent>
              {line.map((token, key) => (
                <span key={`${token}`} {...getTokenProps({ token, key })} />
              ))}
            </LineContent>
          </Line>
        ))}
      </Pre>
    )}
  </Highlight>
)

export default CodeBlock
```

I'm getting started with Typescript,  so maybe there would be a better solution for my usecase?
Anyway, I was thinking about the possibility of using DefinitelyTyped work inside yours, to avoid those typing issues... WDYT?

**Comment by flying-sheep** [comment]
I think your way is correct because this component’s interface is more tightly typed:

`prism-react-renderer` e.g. knows which languages it supports, so its `language` type is `'js' | ...` instead of `string`
