### ISSUE TITLE
Read-me update: Prism import

### ISSUE THREAD

**Issue by arieloO** [FormidableLabs/prism-react-renderer#119]
Prismjs import doesn't work as specified in [read-me #prism](https://github.com/FormidableLabs/prism-react-renderer#prism)

` import Prism from 'prismjs/components/prism-core'; `

This import above doesn't match any file on basic install, I guess it only works if you have prismjs lib installed.

instead you have to import it from 'prism-react-renderer`

` { Prism } from "prism-react-renderer";`

Maybe I missed something in the process, but it does work this way.

**Comment by kitten** [comment]
The instruction here matches the base Prism installation instead: https://unpkg.com/browse/prismjs@1.23.0/components/prism-core.js

So it's meant for cases where you want to create a custom Prism instance from the Prism package and not use the bundled Prisma in prism-react-renderer
