### ISSUE TITLE
Add support for Dockerfile and Shell-Session

### ISSUE THREAD

**Issue by felipecrs** [FormidableLabs/prism-react-renderer#121]
I believe these two languages are common and generic enough to deserve being supported by default.

I created a PR at https://github.com/FormidableLabs/prism-react-renderer/pull/120 to add them in the supported languages list.

However, I noticed that it would not be the only thing needed. As stated on https://github.com/facebook/docusaurus/issues/3559#issuecomment-885767525, it seems that not all themes supports the tokens used in `shell-session` for example:

Palenight:

![image](https://user-images.githubusercontent.com/29582865/126814483-f1b8f749-899e-43f0-9de2-6b47cce04519.png)

GitHub:

![image](https://user-images.githubusercontent.com/29582865/126815622-1d4e18af-1c96-45b5-b575-249515f8a2d4.png)

Dracula:

![image](https://user-images.githubusercontent.com/29582865/126815608-10a31c2d-8859-4e48-8569-d01799407329.png)

**Comment by jasikpark** [comment]
Is there a reason why the associated PR was closed and abandoned? This would be helpful for me in use in my Docusaurus site

**Comment by jasikpark** [comment]
Is language `bash` the recommended alternative to adding support for this?
