### ISSUE TITLE
How to disable selection for Dollar sign in code blocks

### ISSUE THREAD

**Issue by mfridman** [FormidableLabs/prism-react-renderer#122]
Is it possible to have a code block such as:

```shell
$ echo "hello world" | cat 
```

And have the copy button not include the prefixed symbol`$` and space?

Quite often you may want to specify a terminal command, denoted with the `$` identifier .. but not actually have it copied along with the command.

### Got:

<img width="484" alt="CleanShot 2021-07-27 at 16 50 30@2x" src="https://user-images.githubusercontent.com/6278244/127225505-7f7f9737-f2c1-4626-b705-a83993e061cc.png">

### Want:

<img width="482" alt="CleanShot 2021-07-27 at 16 50 40@2x" src="https://user-images.githubusercontent.com/6278244/127225521-fb4cfdd3-c87d-4e42-8047-eeb92608c0d8.png">

**Comment by kitten** [comment]
This could be solved in multiple ways;
 for instance, you could style these with `user-select: none` or make sure to virtually include them in a `:before` pseudo element

**Comment by stfenjobs** [comment]
@mfridman 

hi, my firend 

how to add copy button to the codeblock  like this:
![image](https://user-images.githubusercontent.com/6580897/131673321-1a0700ff-b0da-4c9a-bc42-a9311faf0654.png)
