### ISSUE TITLE
Extra new line at the end of the Highlight component, bug?

### ISSUE THREAD

**Issue by tonywei92** [FormidableLabs/prism-react-renderer#124]
Just tried the `prism-react-renderer`, it's working great, but something odd happens, there is always an extra new line at the end of the code

![image](https://user-images.githubusercontent.com/20355806/128631767-af43c095-4a5d-47f2-9437-d31b84313f53.png)

```jsx
import React from 'react'
import Highlight, { defaultProps } from 'prism-react-renderer'
import theme from "prism-react-renderer/themes/oceanicNext";

export default function CodeBlock({ children, className }) {
  const language = className.replace(/language-/, '')
  console.log('children', children)
  return (
    <Highlight {...defaultProps} theme={theme} code={children} language={language}>
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <pre className={className} style={{ ...style, padding: '20px' }}>
          {tokens.map((line, i) => (
            <div key={i} {...getLineProps({ line, key: i })}>
              {line.map((token, key) => (
                  <span key={key} {...getTokenProps({ token, key })} />
              ))}
            </div>
          ))}
        </pre>
      )}
    </Highlight>
  )
}
```

the `children` props content:

```
children sudo nano /etc/systemd/resolved.conf

asdasd
```

![image](https://user-images.githubusercontent.com/20355806/128631811-3e8d598b-0eb8-4c97-bd6b-4e9b80cec72a.png)

Any idea how to fix it? thanks!

**Comment by kitten** [comment]
Have you checked your input by any chance? it's easy to miss but any trailing newline character will be rendered out and returned to you as a separate line, so often you'll have to either sanitise your input or simply make sure to cut off trailing newline characters, if that's what you'd like to render out.

In the sandbox here you can see how most examples simply trim the input code to avoid trailing and leading newlines: https://codesandbox.io/s/prism-react-renderer-example-u6vhk
