### ISSUE TITLE
add support for Solidity language

### ISSUE THREAD

**Issue by znwhite** [FormidableLabs/prism-react-renderer#133]
It would be great if one of the languages we can pass is "sol" or "solidity". Solidity syntax highlighting would come in really handy for a blog post I am currently writing. Thanks!

**Comment by paulrberg** [comment]
Commenting to cast my support. As of writing this comment, Solidity is among the fastest-growing programming language in the world.

**Comment by nicochatzi** [comment]
PrismJS [has solidity syntax](https://github.com/PrismJS/prism/blob/master/components/prism-solidity.js) 🎉 
You can add it by following the steps in the [FAQ](https://github.com/FormidableLabs/prism-react-renderer#faq)
