### ISSUE TITLE
Aliases representing classes is not applied.

### ISSUE THREAD

**Issue by nortmas** [FormidableLabs/prism-react-renderer#14]
It seems there is an issue with aliases. 
For example here is a rule:
```Prism.languages.insertBefore('php', 'keyword', {
    'delimiter': {
      pattern: /\?>|<\?(?:php|=)?/i,
      alias: 'important'
    },
    'variable': /\$+(?:\w+\b|(?={))/i,
    'package': {
      pattern: /(\\|namespace\s+|use\s+)[\w\\]+/,
      lookbehind: true,
      inside: {
        punctuation: /\\/
      }
    }
  });
```

The alias `important` is not applied. It means there is no class `important` for the `<?php` element. 
However, in the official test it works:
![screen-01-16-13](https://user-images.githubusercontent.com/1155719/45567911-43a75100-b885-11e8-8c56-afbea92c2f38.png)
And it's relevant for all other aliases.

**Comment by kitten** [comment]
Ah, I wasn't aware of those as I've never tested with any language in Prism that was using the alias keyword.

Can you quickly paste something into the Code Sandbox in the readme please? It helps a lot to speed the process of fixing it up :)

Do you know if the alias property can hold arrays of multiple aliases as well by any chance?

**Comment by nortmas** [comment]
Hey! Thank you for the very quick response!

> Can you quickly paste something into the Code Sandbox in the readme please? It helps a lot to speed the process of fixing it up

I'd love to do it but I'm not sure what do you exactly mean about readme file. :) 
Here is the example with the same code but using `prism-react-renderer`: https://codesandbox.io/s/33k5ll1mp?module=%2Fsrc%2Fbasic.js
Hope it can help you a bit.

> Do you know if the alias property can hold arrays of multiple aliases as well by any chance?

Nope, I don't think so. I've checked all the alias entries in `pism/index.js` and haven't found a single array there.

**Comment by nortmas** [comment]
Actually, I forfot to mention what is the main problem :)
These aliases are used by any theme I've downloaded. It means that some code items not highlighted.
here is an example: https://github.com/PrismJS/prism-themes/blob/master/themes/prism-darcula.css
```
.token.delimiter,
.token.boolean,
.token.keyword,
.token.selector,
.token.important,
.token.atrule {
	color: #cc7832;
}
```

**Comment by nortmas** [comment]
Hey @kitten, I'm sorry for disturbing you. Do you have any ideas on how to make it work?
