### ISSUE TITLE
code highlighting does not work in nextjs dev environment

### ISSUE THREAD

**Issue by frostzt** [FormidableLabs/prism-react-renderer#141]
# The problem

I am trying to use `prism-react-renderer` with Nextjs and Chakra-UI, however when I run `next dev` which starts the Nextjs development server, I am not able to see any code that are inside the \``` code block \```. Remember the code itself is not rendered for some reason.

Here is an screenshot of what's happening:
![Empty-code-prism](https://user-images.githubusercontent.com/25434993/152628895-1d044659-bc74-4b14-921d-541a4797f497.png)

However if I build this with `next build` and try again, it shows up:
![after-build-prism](https://user-images.githubusercontent.com/25434993/152628939-45b76525-8478-40b8-b5e9-30fe61198258.png)

# Steps to reproduce
I actually have a repo that clones this issue:
[Prism Code Issue Repo](https://github.com/frostzt/mdxblog/tree/prism-code-issue)

The repo is for something else, however this branch is at the point where it fails. Simply do a `yarn dev` or `npm run dev` (after doing a `npm install` or `yarn install`), and simply open `localhost:3000` and open the first post that should show the issue.

The things that are rendered are in the `MDXComponents` present inside the `/components/MDXComponents` file.

**Comment by sytpb** [comment]
it doesn't work with nextJS ?

**Comment by frostzt** [comment]
Well seems like this was some issue with rendering stuff, if I explicitly return it, it works.
