### ISSUE TITLE
`min-width: max-content` causes change in font size on iOS

### ISSUE THREAD

**Issue by mrseanbaines** [FormidableLabs/prism-react-renderer#145]
I've run into a strange issue where it seems that if I set `min-width: max-content` on a wrapper element, it causes the font size to change. This only seems to happen on mobile (tested on iOS / Safari).

Here's a codesandbox showing the issue: https://codesandbox.io/s/beautiful-booth-kvv76o?file=/src/index.js&resolutionWidth=320&resolutionHeight=675

In desktop browser (Firefox):
<img width="462" alt="Screenshot 2022-02-23 at 11 10 36" src="https://user-images.githubusercontent.com/24367010/155308439-6aa361ea-d8bf-49a3-b19b-fb2dd6742888.png">

On mobile:
<img src="https://user-images.githubusercontent.com/24367010/155308520-cd78279f-f4b1-4187-8879-91f54c132410.PNG" width="50%" />

It doesn't seem to matter if I explicitly set a font size or not, I get the same issue.

I've tried the same example with a raw `pre` tag (without `prism-react-renderer`), and it doesn't have the issue, although, oddly, if I render both the raw `pre` version _as well as_ the `prism-react-renderer` version on the same screen, the raw `pre` version starts showing the issue! 🤯

i.e. this:
```jsx
<pre className="overflow">
  <div className="padding min-width">{code}</div>
</pre>
```

doesn't affect the font size:
<img src="https://user-images.githubusercontent.com/24367010/155309541-6f21b6b4-fd75-4be9-ac36-2e2945bf03c7.PNG" width="50%" />

But this:
```jsx
<pre className="overflow">
  <div className="padding min-width">{code}</div>
</pre>

<br />

<CodeBlock code={code} withMinWidth />
```

_**Does**_ affect font size:
<img src="https://user-images.githubusercontent.com/24367010/155309906-4c4703cc-5dea-41b6-94aa-2512fce37e75.PNG" width="50%" />

**Comment by bencmbrook** [comment]
Just found a fix for this: add [this rule](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust) to your `pre` tag: `-webkit-text-size-adjust: none;`

**Comment by mrseanbaines** [comment]
@bencmbrook you're a legend. Worked like a charm 🙌
