### ISSUE TITLE
Line wrap option

### ISSUE THREAD

**Issue by ameya730** [FormidableLabs/prism-react-renderer#148]
Hi,

I am working on an application that needs to display code on their website. Certain lines that are extracted from the file are quite long. Is there a way to wrap the lines so that I can display them within a div of a certain width.

Regards,
Ameya

**Comment by anthonygore** [comment]
It's possible using CSS.

Let's say you structure your code like this:

```
<Line>
  <LineNumber>...</LineNumber>
  <LineContent>...</LineContent>
</Line>
```

You can use flex on `Line` and use these rules on `LineContent`:

```
white-space: normal;
word-break: break-word;
```

**Comment by anthonygore** [comment]
It can be done with CSS.

Use these rules on your lines:

```
white-space: pre-wrap;
word-break: break-word;
```

**Comment by ameya730** [comment]
Hi Anthony,
Thanks. that worked.
Regards,
Ameya
