### ISSUE TITLE
Add plugins as autolinker

### ISSUE THREAD

**Issue by dtpfl** [FormidableLabs/prism-react-renderer#154]
Hey,

is there a way to add prismjs plugins as autolinker?
https://prismjs.com/plugins/autolinker/

Haven't found a solution yet.
If there isn't a solution existing, this should be a suggestion to add such features, maybe i can help out :)

**Comment by cassieevans** [comment]
Hi there! Bumping this as a feature request - I'm currently using Docusaurus and it would be great to be able to add links in comments.

**Comment by nlkluth** [comment]
Closing this issue as Prism's Autolinker plugin modifies the prism rendered string directly and isn't compatible with the token rendering architecture of prism-react-renderer. You have more control in the render function should you wish to render a token differently.  

If you believe this is a bigger issue, please reopen.
