### ISSUE TITLE
The first example from the documentation doesn't work

### ISSUE THREAD

**Issue by alexander-vashchuk** [FormidableLabs/prism-react-renderer#157]
![Untitled](https://user-images.githubusercontent.com/86713661/173180193-e2cfa574-95ac-49ac-bf38-f0a3d6a2a561.png)

**Comment by alexander-vashchuk** [comment]
Looks like React has a new syntax for creating the root:

```tsx
ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

```

**Comment by gksander** [comment]
This appears to be due to React 18's new API for creating/rendering to the root. We should probably update the README with a note about that.
