### ISSUE TITLE
Changing the theme doesn't work

### ISSUE THREAD

**Issue by pomber** [FormidableLabs/prism-react-renderer#16]
Theme is not updated when I change the `theme` prop. 
Minimal repro: https://codesandbox.io/s/9415mzmr0w

My current workaround is changing the `key` of the `Highlight` component together with the `theme` prop, so the component is mounted again when the theme changes (line 26 in the linked codesandbox).

Sorry I didn't have time to debug it today.

**Comment by kitten** [comment]
To be honest, this was pure laziness on my part 😆 It's an easy fix which I can do asap https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/components/Highlight.js#L32-L34
