### ISSUE TITLE
Is work with nextJS 

### ISSUE THREAD

**Issue by sytpb** [FormidableLabs/prism-react-renderer#164]
i want to use this in my nextjs project . but i wonder to know is it works with NextJS ?

**Comment by diegofrayo** [comment]
It works, you can see a real live example and the source code on my website: https://diegofrayo.vercel.app/blog/my-favorite-music-and-mdx

**Comment by andrei-zgirvaci** [comment]
@diegofrayo It works with Nextjs 12, but not 13. Did you try running it inside a server component?

**Comment by diegofrayo** [comment]
> @diegofrayo It works with Nextjs 12, but not 13. Did you try running it inside a server component?

I didn't
Many libraries that I use (next-mdx-remote for example) have problems with Next.js 13 so for this reason I'm going to upgrade for now

**Comment by diegofrayo** [comment]
> > @diegofrayo It works with Nextjs 12, but not 13. Did you try running it inside a server component?
> 
> I didn't Many libraries that I use (next-mdx-remote for example) have problems with Next.js 13 so for this reason I'm going to upgrade for now

**UPDATE:** I just upgraded to next.js 13, and this library works well as expected along with `next-mdx-remote`
