### ISSUE TITLE
Add Rust language support

### ISSUE THREAD

**Issue by afonsojramos** [FormidableLabs/prism-react-renderer#171]
I am writing to request that Rust language support be added to this repository. Rust is a fast and safe language that is well-suited for projects that require performance and reliability, and its popularity has been rising considerably. I believe that adding Rust language support would benefit the community of users and contributors to this repository.

Please let me know if you have any questions or concerns about adding Rust language support. I look forward to your response. Thank you for considering my request.

**Comment by zrosenbauer** [comment]
@afonsojramos FYI you can add it directly via prism https://github.com/FormidableLabs/prism-react-renderer#faq
