### ISSUE TITLE
Add the new ReactNode children type in React 18

### ISSUE THREAD

**Issue by getellez** [FormidableLabs/prism-react-renderer#175]
We are migrating a project from React 17 to React 18 but Highlighter returns children with Node type instead of ReactNode which is a new children type in React 18. 

I'm getting this error: 

`
'Highlight' cannot be used as a JSX component.
  Its instance type 'Highlight' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import(".../node_modules/@mdx-js/react/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
`

**Comment by alissanguyen** [comment]
Did you manage to fix this issue?
