### ISSUE TITLE
GitHub theme doesn't look like GitHub

### ISSUE THREAD

**Issue by guoyunhe** [FormidableLabs/prism-react-renderer#178]
```jsx
import React from 'react';

function App() {
  return <div className="app">
    <h1>Hello, World</h1>
  </div>;
}
```

GitHub website:

![image](https://user-images.githubusercontent.com/5836790/221112335-e925983d-acf4-4801-b862-a5ba8d770273.png)

Prism-react-render:

![image](https://user-images.githubusercontent.com/5836790/221112600-01505df8-0627-449d-a9a9-755c84efe1fa.png)

**Comment by rilakumma** [comment]
we are using [this GH theme ](https://github.com/PrismJS/prism-themes/blob/447479fc7b2be2051fe27e561aceed7cc87a589f/themes/prism-ghcolors.css) , it was created 4 years ago tho so maybe GH has since updated their colors
