### ISSUE TITLE
Add language customization question in issue/pr template

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/prism-react-renderer#184]
Many of the issues and pull requests in this repository revolve around adding custom languages. We have a section in the FAQ that discusses how to do this for any language that’s not included in the small side of default ones.

Perhaps we could add a question or suggestion, more explicitly in our templates to help people see this before opening an issue or pull request referring to https://github.com/FormidableLabs/prism-react-renderer#faq ?

**Comment by carloskelly13** [comment]
Great idea, README updated → https://github.com/FormidableLabs/prism-react-renderer#custom-language-support
