### ISSUE TITLE
README.md link to supported langages broken (`includeLangs.js`)

### ISSUE THREAD

**Issue by slorber** [FormidableLabs/prism-react-renderer#190]
Multiple links in the README are now broken. 

> By default `prism-react-renderer` only includes an [arbitrary subset of the languages](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) that Prism supports. You can add support for more by including their definitions from the main `prismjs` package:

> This library tokenises code using Prism and provides a small render-props-driven
component to quickly render it out into React. This is why it even works with
React Native! It's bundled with a modified version of Prism that won't pollute
the global namespace and comes with
[a couple of common language syntaxes](./src/vendor/prism/includeLangs.js).

> This is the language that your code will be highlighted as. You can see a list
of all languages that are supported out of the box [here](./src/vendor/prism/includeLangs.js).

We also used this link on the Docusaurus website and looking for a replacement, do you have any to suggest?

https://github.com/facebook/docusaurus/pull/8904

**Comment by carloskelly13** [comment]
@slorber  Hi :wave: The languages are at https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/generate-prism-languages/index.ts#L9-L24.

Those are the top-level languages. Any dependent languages from that list are also included. Dependents are identified by PrismJS. For example `jsx` will also include `js`.

**Comment by slorber** [comment]
Thanks @carloskelly13 🙏

**Comment by ustun-ed** [comment]
@carloskelly13 is there a particular reason JSON is not in that default bundle? I can open a new issue if it is an oversight.

**Comment by ustun-ed** [comment]
Also opened a PR to fix the broken links: https://github.com/FormidableLabs/prism-react-renderer/pull/207
