### ISSUE TITLE
Themes are missing in 2.0 release

### ISSUE THREAD

**Issue by sebdanielsson** [FormidableLabs/prism-react-renderer#194]
My site just broke with the following error message:

`Error: Cannot find module 'prism-react-renderer/themes/dracula'`

After some digging I found that i only have these files after installing 2.0:

- dist
    - index.d.ts
    - index.js
    - index.js.map
    - index.mjs
    - index.mjs.map
- LICENCE
- package.json

Is this intentional? And if it is, how do I import the previously bundled themes?

Thanks!☺️

**Comment by ltribolet** [comment]
You can update your docusaurus config like so:

```js
const themes = require('prism-react-renderer').themes;
const lightCodeTheme = themes.github;
const darkCodeTheme = themes.dracula;
```

**Comment by carloskelly13** [comment]
Hi 👋🏻 Yes, it is now part of the package. You can do `import { themes } from 'prism-react-renderer'`. A good shout to make sure the documentation better reflects this change in 2.0. Thanks!

**Comment by digitaltopo** [comment]
`import { themes } from 'prism-react-renderer'`

Module '"prism-react-renderer"' has no exported member 'themes'.  :thinking: 

`"prism-react-renderer": "^2.0.0",`

**Comment by noraj** [comment]
It would be nice to document breaking changes in a changelog file.

**Comment by elliot-at-looker** [comment]
@digitaltopo +1 to your error, I am getting the same thing. What was the fix?
