### ISSUE TITLE
Prism plugins

### ISSUE THREAD

**Issue by montogeek** [FormidableLabs/prism-react-renderer#2]
Are Prism plugin supported? I guess not since they operate in DOM Nodes.

**Comment by kitten** [comment]
No, they’re unfortunately not :)

The point is more or less that it’ll be a quick affair to implement most visual features from scratch, (although libraries on top of this one aren’t out of the question of course.)

The CodeSandbox example has a small line number indicator for instance.

**Comment by detj** [comment]
@kitten I'm wondering what are the challenges in supporting existing Prism plugins. And could you share the CodeSandbox example link ?

**Comment by kitten** [comment]
@detj The challenge is that this is purely intended to render to React with no output that is target by Prism's existing plugins. So you'd choose this library specifically to build a specific style of code highlighting in React :) So it's about granularity

**Comment by JiangWeixian** [comment]
maybe provide a hooks version just like https://github.com/tannerlinsley/react-table, will be easy to implement a plugin, just like `useExpand` in `useTable` in https://github.com/tannerlinsley/react-table

```tsx
const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow,
    state: { expanded },
  } = useTable(
    {
      columns: userColumns,
      data,
    },
    useExpanded // Use the useExpanded plugin hook
  )
```
