### ISSUE TITLE
Prism type not assignable to PrismLib prop type

### ISSUE THREAD

**Issue by smartmike** [FormidableLabs/prism-react-renderer#203]
Hey! 👋

I have an typescript error passing `Prism` as a prop to `Highlight`. This happens on both Prism imported from `prismjs` and the exported Prism from `prism-react-renderer`

Error:
```
Type 'typeof import("./node_modules/@types/prismjs/index")' is not assignable to type 'PrismLib'.
  Types of property 'languages' are incompatible.
    Type 'Languages' is not assignable to type 'LanguagesDict'.
      'string' index signatures are incompatible.
        Type 'Grammar' is not assignable to type 'PrismGrammar'.
          Type 'GrammarRest' is not assignable to type 'PrismGrammar'.
            Index signature for type 'string' is missing in type 'GrammarRest'.ts(2322)
```

Reproducible sandbox:
https://codesandbox.io/s/sweet-fire-jmfge6?file=/src/App.tsx

<img width="541" alt="image" src="https://user-images.githubusercontent.com/307552/236190157-c6e60cdd-323d-4032-b751-bfa9071e48db.png">

Please let me know if you need more info, or if I have missed something :)

**Comment by carloskelly13** [comment]
Good catch, we'll get this fixed up.
