### ISSUE TITLE
Import type PrismTheme

### ISSUE THREAD

**Issue by JosueDLA** [FormidableLabs/prism-react-renderer#206]
Hello, I just migrated to v2 and im wondering how to import the type PrismTheme. 

```javascript
import { PrismTheme } from "prism-react-renderer";
```

In v1.3.5 it was posible to use the import PrismTheme but currently im fasing the following error.

```
prism-react-renderer"' declares 'PrismTheme' locally, but it is not exported
```

**Comment by bryceknz** [comment]
Hi @JosueDLA, thank you for reporting this issue. This was fixed in version `2.0.6` by the following PR: https://github.com/FormidableLabs/prism-react-renderer/pull/216. Please update to a newer version and let us know if you still have this issue.
