### ISSUE TITLE
Need python support

### ISSUE THREAD

**Issue by AishwaryaMurade** [FormidableLabs/prism-react-renderer#210]
It does not support python language

**Comment by cedarbaum** [comment]
You can manually add it from the main `prismjs` package (this is detailed here: https://github.com/FormidableLabs/prism-react-renderer#custom-language-support):

```
npm install prismjs
```

and then:

```javascript
(typeof global !== "undefined" ? global : window).Prism = Prism
require("prismjs/components/prism-python")
```
