### ISSUE TITLE
Import type Language

### ISSUE THREAD

**Issue by Deveesh-Shetty** [FormidableLabs/prism-react-renderer#211]
I was following a tutorial for NextJS and I got this error while importing the `Language` type

Any other way to import it in the new version?

![image](https://github.com/FormidableLabs/prism-react-renderer/assets/89470104/2a71a439-4f7f-496e-823b-61243fedc9c4)

**Comment by urbanobaz** [comment]
same @Deveesh-Shetty

**Comment by Deveesh-Shetty** [comment]
If you are stuck I suggest you downgrade to version 1.3.5 I did the same, till we find a solution

```
npm install prism-react-renderer@1.3.5
```
or
```
yarn add prism-react-renderer@1.3.5
```

**Comment by urbanobaz** [comment]
perfect! I tried it and it's working. Thank you @Deveesh-Shetty
