### ISSUE TITLE
v1 to v2 Migration Guide

### ISSUE THREAD

**Issue by RudraSen2** [FormidableLabs/prism-react-renderer#217]
It would be good if this project had a v1 to v2 Migration Guide which will help us to migrate successfully to v2 as the APIs were changed and it is challenging to look for the changes in the API by looking at the README. Any help would be appreciated.

**Comment by rohrlaf** [comment]
## Change module imports

```diff
- import Highlight, { defaultProps } from "prism-react-renderer";
+ import { Highlight } from "prism-react-renderer"

const Content = (
-  <Highlight {...defaultProps} code={exampleCode} language="jsx">
+  <Highlight code={exampleCode} language="jsx">
```

## Check language support

> By default prism-react-renderer only includes a [base set of languages](https://github.com/FormidableLabs/prism-react-renderer/blob/c914fdea48625ba59c8022174bb3df1ed802ce4d/packages/generate-prism-languages/index.ts#L9-L23) that Prism supports. Depending on your app's build system you may need to await the import or use require to ensure window.Prism exists before importing the custom languages.

See: https://github.com/FormidableLabs/prism-react-renderer#custom-language-support

Install `prismjs` (if not available yet):

```sh
# npm
npm install --save prismjs
# yarn
yarn add prismjs
# pnpm
pnpm add prismjs
```

Add language component:

```jsx
import { Highlight, Prism } from "prism-react-renderer";

(typeof global !== "undefined" ? global : window).Prism = Prism
await import("prismjs/components/prism-applescript")
/** or **/
require("prismjs/components/prism-applescript")
```

**Comment by RudraSen2** [comment]
> ## Change module imports
> ```diff
> - import Highlight, { defaultProps } from "prism-react-renderer";
> + import { Highlight } from "prism-react-renderer"
> 
> const Content = (
> -  <Highlight {...defaultProps} code={exampleCode} language="jsx">
> +  <Highlight code={exampleCode} language="jsx">
> ```
> 
> ## Check language support
> > By default prism-react-renderer only includes a [base set of languages](https://github.com/FormidableLabs/prism-react-renderer/blob/c914fdea48625ba59c8022174bb3df1ed802ce4d/packages/generate-prism-languages/index.ts#L9-L23) that Prism supports. Depending on your app's build system you may need to await the import or use require to ensure window.Prism exists before importing the custom languages.
> 
> See: https://github.com/FormidableLabs/prism-react-renderer#custom-language-support
> 
> Install `prismjs` (if not available yet):
> 
> ```shell
> # npm
> npm install --save prismjs
> # yarn
> yarn add prismjs
> # pnpm
> pnpm add prismjs
> ```
> 
> Add language component:
> 
> ```js
> import { Highlight, Prism } from "prism-react-renderer";
> 
> (typeof global !== "undefined" ? global : window).Prism = Prism
> await import("prismjs/components/prism-applescript")
> /** or **/
> require("prismjs/components/prism-applescript")
> ```

so is this the whole migration guide?

**Comment by chris48s** [comment]
I found I also needed to update theme imports e.g:

```diff
- const theme = require('prism-react-renderer/themes/github')
+ const theme = require('prism-react-renderer').themes.github
```
