### ISSUE TITLE
Adding new languages?

### ISSUE THREAD

**Issue by lukepighetti** [FormidableLabs/prism-react-renderer#24]
How do I add Dart?

https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/components/prism-dart.min.js

**Comment by i-am-the-slime** [comment]
Well, how?

**Comment by softmarshmallow** [comment]
re open please

**Comment by kitten** [comment]
There are several other issues that talk about / ask how to / and contain instructions on adding other Prism syntaxes. Please refer to those:

- https://github.com/FormidableLabs/prism-react-renderer/issues/53
- https://github.com/FormidableLabs/prism-react-renderer/issues/85
- https://github.com/FormidableLabs/prism-react-renderer/issues/80#issuecomment-623348605
