### ISSUE TITLE
Cursor jumps while writing

### ISSUE THREAD

**Issue by alicemacl** [FormidableLabs/prism-react-renderer#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Bug report

```markdown
When writing code in the block the cursor jumps. Using the latest version.
```

![codeblock-text-pointer](https://github.com/user-attachments/assets/36e8d498-3d6f-4cc0-92b4-5beb86cf35db)

**Comment by kavita-ng** [comment]
@alicemacl - Hey, I have been trying to replicate this behaviour but so far have been unsuccessful. Here's a [code sandbox](https://codesandbox.io/p/sandbox/y9pwc2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm15dotlw00063b6ir4007rr1%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm15dotlw00023b6iio7xw1i4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm15dotlw00033b6ij7wef9d7%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm15dotlw00053b6ib51ghf0x%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm15dotlw00023b6iio7xw1i4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm15dotlv00013b6i08wj5xcz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm15dotlw00023b6iio7xw1i4%2522%252C%2522activeTabId%2522%253A%2522cm15dotlv00013b6i08wj5xcz%2522%257D%252C%2522cm15dotlw00053b6ib51ghf0x%2522%253A%257B%2522id%2522%253A%2522cm15dotlw00053b6ib51ghf0x%2522%252C%2522activeTabId%2522%253A%2522cm15dpmmn001b3b6ie02iklad%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm15dotlw00043b6iwbdqxqvt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm15dpmmn001b3b6ie02iklad%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm15dotlw00033b6ij7wef9d7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm15dotlw00033b6ij7wef9d7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with the same code shown in your issue report. 

Can you please provide more information about your use case? Is editing the content resulting in a React state update,  causing a conflict? Are you able to see this behaviour irrespective of theme / language / code size?
