### ISSUE TITLE
How to highlight lines

### ISSUE THREAD

**Issue by alfieqashwa** [FormidableLabs/prism-react-renderer#26]
Hello, I'm using prism-react-renderer in .md and mdx using gatsbyjs. I can't find the documentation example how to add lines also highlight the line.

**Comment by alfieqashwa** [comment]
Hello, I'm using prism-react-renderer in .md and mdx using gatsbyjs. I can't find the documentation example how to add lines also highlight the line.

**Comment by filoxo** [comment]
Here's how I managed to achieve line highlighting using prism-react-renderer in my gatsby-mdx blog.

https://github.com/filoxo/blog/commit/3862bb4f5f5d4ebfafa3f773b7c1687fc8ca5bea

**Comment by dimitrisnl** [comment]
@filoxo 	Just note that your approach isn't working properly when there is a scrollbar

![Screen Shot 2019-03-26 at 6 17 14 PM](https://user-images.githubusercontent.com/4951004/55014355-7fb92c80-4ff3-11e9-9014-56c4415bdad1.png)

I was looking for a way to solve this, and adding a wrapper element that overflows (div) before the `pre` element works great.

**Comment by filoxo** [comment]
@dimitrisnl I wouldn't say it isn't working properly. It's a known styling "inconvenience" that even [Gatsby docs provide a solution for the overflow scroll styling](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#optional-add-line-highlighting-styles). It's pretty minor when considering that it is only a visual help, and does nothing for accessibility or document semantics.

The solution is purely in the styling. You could add a wrapper element like you did, or you could allow the `pre` text to wrap (which React docs do https://reactjs.org/tutorial/tutorial.html#making-an-interactive-component ), or like me you could just not care about such a minor thing.

**Comment by kitten** [comment]
I think there's been a sufficiently good answer and it's basically a UI problem on top of prism-react-renderer and not a library concern.

So there's a code sample, you can take it to StackOverflow, or we can open an issue to add more examples to the docs or repo 👍

**Comment by wwwebman** [comment]
I migrated from [gatsby-remark-prismjs ](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs) and was searching for something backward compatible to [highlight-* marks](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/#line-highlighting).

The working and simple solution would be:
```jsx
import React from 'react';
import Highlight, { defaultProps } from 'prism-react-renderer';

const isHighlightedLine = (line, mark = '// highlight-next-line') =>
  line?.some((prevLine) => {
    return prevLine?.content === mark;
  });

export default ({ children, className }) => {
  const language = className.replace(/language-/, '');

  return (
    <Highlight {...defaultProps} code={children.trim()} language={language}>
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <pre
          className={className}
          style={{ ...style }}
          data-language={language}
        >
          {tokens.map((line, i) => {
            const lineProps = getLineProps({ line, key: i });
            const classNameArr = [lineProps.className];

            if (isHighlightedLine(line)) {
              return null;
            }

            if (isHighlightedLine(tokens?.[i - 1])) {
              classNameArr.push('your-awesome-highlight-class');
            }

            const finalLineProps = {
              ...lineProps,
              className: classNameArr.join(' '),
            };

            return (
              <div key={i} {...finalLineProps}>
                {line.map((token, key) => (
                  <span key={key} {...getTokenProps({ token, key })} />
                ))}
              </div>
            );
          })}
        </pre>
      )}
    </Highlight>
  );
};
```

Usage (`index.mdx`):
```md
#### Implementation

```jsx
// highlight-next-line
const Component = ({}) => null);
...
```

**Comment by maxcell** [comment]
Hey folks! Though this issue is dead, I just wanted to share that I ended up write up a synthesis of what folks have shared here! This particular feature for me was very important and I am glad to have it back <3. Thank you @filoxo for sharing your solution, I've made sure to credit you at the end https://prince.dev/blog/highlight-with-react

**Comment by EllisMin** [comment]
In case anyone wants to use highlighting in **gatsby.js** with

`// highlight-line`: highlighting current line
`// highlight-start` & `// highlight-end`: highlighting lines between

I would like to share my solution

```jsx
import React from "react"
import Highlight, { defaultProps } from "prism-react-renderer"

let highlightStart = false
const highlightClassName = "gatsby-highlight-code-line"

const highlightLine = (lineArray, lineProps) => {
  lineArray.forEach((line, i) => {
    const content = line.content

    // Code line contains trimmed "//highlight-line"
    if (content.replace(/\s/g, "") === "//highlight-line") {
      lineProps.className = `${lineProps.className} ${highlightClassName}`
      lineArray.splice(i, 1)
    }

    // Stop highlighting
    if (
      !!highlightStart &&
      content.replace(/\s/g, "") === "//highlight-end" &&
      (lineArray.length === 2 || lineArray.length === 3)
    ) {
      highlightStart = false
      // Remove comment & empty line
      lineArray.length = 0
      lineProps.className = ""
    }

    // Highlight lines after //highlight-start
    if (!!highlightStart) {
      // Add highlight-class
      lineProps.className = `${lineProps.className} ${highlightClassName}`
    }

    // Start highlighting after "//highlight-start"
    if (
      content.replace(/\s/g, "") === "//highlight-start" &&
      lineArray.length === 3
    ) {
      highlightStart = true
      lineArray.length = 0
      lineProps.className = ""
    }
  })
}

const Code = ({ codeString, language }) => {
  return (
    <Highlight
      {...defaultProps}
      code={codeString}
      language={language}
      theme={false}
    >
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <div className="gatsby-highlight" data-language={language}>
          <pre className={className} style={style}>
            {tokens.map((line, i) => {
              const lineProps = getLineProps({ line, key: i })
              highlightLine(line, lineProps)
              return (
                <div {...lineProps} key={i}>
                  {line.map((token, key) => (
                    <span {...getTokenProps({ token, key })} />
                  ))}
                </div>
              )
            })}
          </pre>
        </div>
      )}
    </Highlight>
  )
}

export default Code
```

**Styling**
```scss
.gatsby-highlight-code-line {
  display: block;
  margin-left: -0.6rem;
  padding-left: 0.4rem;
  background-color: #fafafa
  border-left: 2px solid #ffd700
}
```

**Comment by sahilrajput03** [comment]
If anybody wants to lookat live code of what @EllisMin suggested, take a look @ [codesandbx example here](https://codesandbox.io/s/prism-react-renderer-example-line-highlight-yikes-dckbh?file=/src/Basic.js) .

The original [codesandbox example](https://codesandbox.io/s/prism-react-renderer-example-u6vhk) was cloned from [prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer#usage).

Thanks a lot @EllisMin .
