### ISSUE TITLE
Add fallback for unsupported languages

### ISSUE THREAD

**Issue by Kosai106** [FormidableLabs/prism-react-renderer#3]
Whenever I pass `language` using a prop instead of a straight up string, I get the error `TypeError: Cannot read property 'rest' of undefined`

#### Working

```
<Highlight {...defaultProps} code={sample.code} language="jsx">
  {({ className, style, tokens, getLineProps, getTokenProps }) => (
    <pre className={className} style={style}>
      {tokens.map((line, i) => (
        <div {...getLineProps({ line, key: i })}>
          {line.map((token, key) => (
            <span {...getTokenProps({ token, key })} />
          ))}
        </div>
      ))}
    </pre>
  )}
</Highlight>
```

#### Broken

```
<Highlight {...defaultProps} code={sample.code} language={sample.language}>
  {({ className, style, tokens, getLineProps, getTokenProps }) => (
    <pre className={className} style={style}>
      {tokens.map((line, i) => (
        <div {...getLineProps({ line, key: i })}>
          {line.map((token, key) => (
            <span {...getTokenProps({ token, key })} />
          ))}
        </div>
      ))}
    </pre>
  )}
</Highlight>
```

**Comment by Kosai106** [comment]
Update: So it happens because some of my languages are apparently not supported by the package, despite Prism having support for them.

**Comment by kitten** [comment]
I suppose we should add a warning when a language is unsupported or add a fallback :+1:

**Comment by kitten** [comment]
Would this be sufficient for your purposes? https://github.com/FormidableLabs/prism-react-renderer/pull/4

The result is that when an unsupported language is used, the output is styled "plainly" so basically without syntax highlights.

**Comment by Kosai106** [comment]
That should work perfectly for my usecase - Thank you!
