### ISSUE TITLE
Cannot read property 'languages' of undefined

### ISSUE THREAD

**Issue by joaomilho** [FormidableLabs/prism-react-renderer#30]
I'm simply rendering a simple example:

```jsx
<Highlight language="jsx">
  {highlight => <pre>/* your JSX here! */</pre>}
</Highlight>
```

and I get:

![Screenshot 2019-03-14 at 12 49 31](https://user-images.githubusercontent.com/308196/54354770-c142f280-4657-11e9-841e-9e64e9ba992b.png)

Tried to install Prism on its own, but looking at the code it seems Prism is not even being imported.

**Comment by joaomilho** [comment]
So, passing Prism as a prop seems to works, but it's still strange it doesn't have a default prop for that.

**Comment by satya164** [comment]
I think `Prism` should be available globally by default (that's what happens when you import it)

**Comment by kitten** [comment]
Sorry, didn't see this issue before.

You have to apply the `defaultProps` or provide your own `Prism` prop and theme as described in the readme: https://github.com/FormidableLabs/prism-react-renderer#usage
