### ISSUE TITLE
Add Github Theme in the list of themes

### ISSUE THREAD

**Issue by nitish24p** [FormidableLabs/prism-react-renderer#32]
I was using `prism-react-renderer` and had to manually create the github theme, was wondering if this can be added in the list of themes.
<img width="708" alt="Screen Shot 2019-04-24 at 3 04 37 AM" src="https://user-images.githubusercontent.com/13037986/56617629-08040f00-663e-11e9-8b1d-5a0aa1a02427.png">

**Comment by kitten** [comment]
Yes of course 👌 I'd totally merge a PR adding the Github theme!

**Comment by peduarte** [comment]
Has this been released to npm?
