### ISSUE TITLE
How to display an object

### ISSUE THREAD

**Issue by siriwatknp** [FormidableLabs/prism-react-renderer#35]
For example, I have this object stored in variable
```
const object = {
   a: 'hello',
   b: 'world',
}
```

I want to display with Highlight, how do I do that? (I don't want to use JSON.stringify() because the result has "")

**Comment by kitten** [comment]
There's multiple things you could try, like running the stringified data through prettier or find a different printer than JSON.stringify, but this is mainly a question for forums or StackOverflow and out of scope 😀
