### ISSUE TITLE
Single empty line breaks are ignored

### ISSUE THREAD

**Issue by Ehesp** [FormidableLabs/prism-react-renderer#36]
I'm rendering some markdown line so:

```
import auth from '@react-native-firebase/auth';
import database from '@react-native-firebase/database';
 
async function onCreateAccount() {
  // Get the users ID
  const uid = auth().currentUser.uid;
  // ..
```

The rendering works fine, however there is no line break happening between the imports/function:

![image](https://user-images.githubusercontent.com/842078/57016649-286e3380-6c13-11e9-8988-7d2640218559.png)

It looks like the line `token plain` child is an empty string, rather than a string with a single space. I'm able to get around this by doing:

```js
<code>
              {tokens.map((line, i) => {

                // Ensure blank lines/spaces drop onto a new line
                if (line.length === 1 && line[0].content === '') {
                  line[0].content = ' ';
                }

                return (
                  <div {...getLineProps({ line, key: i })}>
                    {line.map((token, key) => {
```

Not sure if it's a bug or something my end? There doesn't seem to be an issue when it's already within a line.

**Comment by airjp73** [comment]
I managed to fix this by adding this style to my css. Turns out there were elements generated for those empty lines, but they weren't showing up because there was nothing in them.

```css
.token-line:not(:last-child) {
  min-height: 1rem;
}
```

The `:not(:last-child)` part is because there was always an extra empty line at the end of the block.

**Comment by sebpearce** [comment]
I'm getting around the extra empty line at the end of the block by doing:
```javascript
{line.map((token, key) => {
  if (key !== line.length - 1 || !token.empty) {
    return <span {...getTokenProps({ token, key })} />
  }
})}
```
(Slightly tricky to parse if you're like me but `!A || !B` is equivalent to `!(A && B)`.)

**Comment by kitten** [comment]
Sorry for the late reply; This can also usually be prevented by adding an empty inline-block div, but this hasn't been documented well.
I'll close this issue for now, since it's stale though :)

**Comment by rwieruch** [comment]
I had a similar issue and the solution by @Ehesp fixed it for me. I think this is not in this library yet. See when I use the following markdown:

```
import abc from 'abc';

import zoo from 'zoo';
```

I get rendered what I wished for:

```
import abc from 'abc';

import zoo from 'zoo';
```

But when I copy and paste the code to my editor/IDE, I get:

```
import abc from 'abc';
import zoo from 'zoo';
```

without the line break. I can see it also on my blog that there is nothing "selected" as line in between:

![Screenshot 2020-04-28 at 14 18 42](https://user-images.githubusercontent.com/2479967/80486284-32785e80-895b-11ea-86d4-8b38dbbaaa06.png)

However, when I use the solution by @Ehesp with:

```
// Ensure blank lines/spaces drop onto a new line
if (line.length === 1 && line[0].content === '') {
  line[0].content = ' ';
}
```

it preserves the empty line when copy and pasting the code and it also shows it as something "empty" selected on my blog:

![Screenshot 2020-04-28 at 14 20 21](https://user-images.githubusercontent.com/2479967/80486423-6e132880-895b-11ea-930b-c8766d5cff55.png)

I guess more people have this problem without noticing. Just wanted to mention it here again and thank @Ehesp 👍

**Comment by dimitrisraptis96** [comment]
@rwieruch 's solution worked like a charm! 

One small enhancement can achieved be adding the following check to delete the extra ending line: 

```javascript
{tokens.map((line, i) => {
    if (
      line.length === 1 &&
      line[0].content === "" &&
      i < tokens.length - 1         // skips the ending empty line
    ) {
      line[0].content = " "
    }
    return (...)
})}

```

**Comment by cesarvarela** [comment]
In my case, when used with mdx this was consistently adding an empty new line to every code block, so:
```
.token-line:last-child {
    display: none;
}
```

**Comment by benedictdudel** [comment]
Since @domharrington solution removes every empty line (not just the last line), I came up with the following solution to get rid of the last empty line:

```javascript
{tokens.slice(0, -1).map((line, i) => (
  <div key={i} {...getLineProps({ line, key: i })}>
    {line.map((token, key) => (
      <span key={key} {...getTokenProps({ token, key })} />
    ))}
  </div>
))}
```

Note: I added `slice(0, -1)` before iterating all `tokens`.
