### ISSUE TITLE
Publish latest to NPM

### ISSUE THREAD

**Issue by wagerfield** [FormidableLabs/prism-react-renderer#38]
I would like to use the [GitHub theme](https://github.com/FormidableLabs/prism-react-renderer/blob/master/themes/github.js) that was added about a month ago, but it's not been published to NPM. The latest version on NPM is `0.1.6` and was published 3 months ago—prior to the GitHub theme being added.

Many thanks for making such an awesome library!

**Comment by malcolm-kee** [comment]
@wagerfield as a workaround I think you can just copy the file into your folder and then migrate later?
