### ISSUE TITLE
Pass react children instead of a code string

### ISSUE THREAD

**Issue by benjamingeorge** [FormidableLabs/prism-react-renderer#43]
Is there any way to not use a string as a code block?  Can the children I pass be converted automatically.  When having multiple code blocks in a component having un-indent the code in the strings seems bad. to get the code blocks to look correct in the browser i have to do this:
<img width="323" alt="Screen Shot 2019-07-25 at 8 02 23 PM" src="https://user-images.githubusercontent.com/1595732/61918488-2ddbd100-af17-11e9-9499-84322c02e26e.png">

I would like to be able to just pass react components and have them converted automatically so I don't have to worry about indentation.  
<img width="322" alt="Screen Shot 2019-07-25 at 8 03 35 PM" src="https://user-images.githubusercontent.com/1595732/61918555-61b6f680-af17-11e9-8bfb-53a4fadc3dae.png">

Is this possible?

**Comment by satya164** [comment]
Maybe you can use `dedent` so you don't have to do it manually
