### ISSUE TITLE
Document Line Numbers Snippet

### ISSUE THREAD

**Issue by karlhorky** [FormidableLabs/prism-react-renderer#45]
Hey there!

Would be cool to add a small stub to the Readme to document adding line numbers either via either of the following methods:

- [the CodeSandbox demo - `src/basic.js`](https://codesandbox.io/s/00o4wx0jqv) - something like the code below
- [@kitten: "I have another snippet somewhere that has line numbers which I can upload later"](https://github.com/satya164/react-simple-code-editor/issues/10#issuecomment-433340048)

Would the `prism-react-renderer` team be open to this?

---

**CodeSandbox version**

```js
import React from 'react'
import styled from 'styled-components'
import Highlight, { defaultProps } from 'prism-react-renderer'
import theme from 'prism-react-renderer/themes/nightOwl'

const exampleCode = `
(function someDemo() {
  var test = "Hello World!";
  console.log(test);
})();

return () => <App />;
`.trim()

const LineNo = styled.span`
  display: inline-block;
  width: 2em;
  user-select: none;
  opacity: 0.3;
`

const Pre = styled.pre`
  text-align: left;
  margin: 1em 0;
  padding: 0.5em;

  & .token-line {
    line-height: 1.3em;
    height: 1.3em;
  }
`

const Basic = () => (
  <Highlight {...defaultProps} theme={theme} code={exampleCode} language="jsx">
    {({ className, style, tokens, getLineProps, getTokenProps }) => (
      <Pre className={className} style={style}>
        {tokens.map((line, i) => (
          <div {...getLineProps({ line, key: i })}>
            <LineNo>{i + 1}</LineNo>
            {line.map((token, key) => <span {...getTokenProps({ token, key })} />)}
          </div>
        ))}
      </Pre>
    )}
  </Highlight>
)

export default Basic
```

**Comment by karlhorky** [comment]
Ah the CodeSandbox version fails at 1000+ lines (I guess some kind of hardcoded margin or width):

![Screen Shot 2019-08-19 at 15 45 07](https://user-images.githubusercontent.com/1935696/63270413-66fa2d80-c298-11e9-9695-10ba9f606ce1.png)

**Comment by karlhorky** [comment]
I guess this could be fixed with a function to determine the width relative to the number of digits in the count of the lines of code:

![Screen Shot 2019-08-19 at 16 02 35](https://user-images.githubusercontent.com/1935696/63271641-e426a200-c29a-11e9-8c87-1f85a4ed7643.png)

![Screen Shot 2019-08-19 at 16 02 22](https://user-images.githubusercontent.com/1935696/63271647-e7ba2900-c29a-11e9-8f19-6a8fc9855fe8.png)

![Screen Shot 2019-08-19 at 16 02 01](https://user-images.githubusercontent.com/1935696/63271664-edb00a00-c29a-11e9-8746-80acbb99ec0c.png)

![Screen Shot 2019-08-19 at 16 01 44](https://user-images.githubusercontent.com/1935696/63271671-f0aafa80-c29a-11e9-9441-1050ec473e7d.png)


```js
function getLineNoWidth(code) {
  return (
    0.5 + code
      .split(/\r\n|\r|\n/) // Split by newlines
      .length // Get number of lines
      .toString().length * // Get number of digits
    // Reduce by 20%
    0.7
  );
}

const LineNo = styled.span`
  display: inline-block;
  width: ${getLineNoWidth(exampleCode)}em;
  user-select: none;
  opacity: 0.3;
`;
```

**Comment by kitten** [comment]
It'd be great to add this to the readme! Sorry for the late reply

**Comment by huy-nguyen** [comment]
I tried @karlhorky's solution and encounter a problem. It looks like the last element of `tokens` is an empty line that looks like this: 
```js
[{types: ["plaint"], content: "", empty: true}]
```
If you don't add line numbering, this last line is not visible. However, the addition of the `<LineNo/>` React element causes this line to always be visible, leading to one extra empty line always showing up in every code block.
My solution was to add a conditional check for for this empty `line` and also remove the styling for `.token-line` inside the `Pre` styled-component, so here's how it looks (without the dynamic line number offset):

```js
import React from 'react'
import styled from 'styled-components'
import Highlight, { defaultProps } from 'prism-react-renderer'
import theme from 'prism-react-renderer/themes/nightOwl'

const exampleCode = `
(function someDemo() {
  var test = "Hello World!";
  console.log(test);
})();

return () => <App />;
`.trim()

const LineNo = styled.span`
  display: inline-block;
  width: 2em;
  user-select: none;
  opacity: 0.3;
`

const Pre = styled.pre`
  text-align: left;
  margin: 1em 0;
  padding: 0.5em;
`

const Basic = () => (
  <Highlight {...defaultProps} theme={theme} code={exampleCode} language="jsx">
    {({ className, style, tokens, getLineProps, getTokenProps }) => (
      <Pre className={className} style={style}>
        {tokens.map((line, i) => {
            const lineNumberElem =
              line.length === 1 && line[0].empty === true ? null : (
                <LineNo>{i + 1}</LineNo>
              );

            return (
              <div key={i} {...getLineProps({ line, key: i })}>
                {lineNumberElem}
                {line.map((token, key) => (
                  <span key={key} {...getTokenProps({ token, key })} />
                ))}
              </div>
            );
          })}
      </Pre>
    )}
  </Highlight>
)

export default Basic
```

**Comment by karlhorky** [comment]
Ah cool, yeah if you have a better version that deals with edge cases let's use that!

**Comment by kitten** [comment]
If anyone's open to adding this to the readme, that'd probably help :) I haven't found time though to update some readmes yet

**Comment by karlhorky** [comment]
Working on a PR now.

**Comment by karlhorky** [comment]
@huy-nguyen I haven't been able to reproduce the issue that you mentioned with the "last line". But good tip about the alignment with flexbox. I think I will use either that or grid to make the solution simpler.

**Comment by karlhorky** [comment]
Ok PR up: #76 

cc @kitten
