### ISSUE TITLE
Adding Out of the Box Languages

### ISSUE THREAD

**Issue by dan-auth0** [FormidableLabs/prism-react-renderer#53]
Howdy :) Thank you very much for this excellent package. I am creating a Gatsby MVP for a giant blog and using this package instead of the remark plugin sped up the rendering process.

We have a lot of languages that are not part of the out of the box list, such as Kotlin and C#. Could you please provide me some guidance on how to enable them?

https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

Thank you in advance for your time.

**Comment by dan-auth0** [comment]
I think I got it 👍 I wasn't understanding the docs too well but after more experimentation the following worked in my `gatsby-browser.js` file: 

```javascript
import React from "react";
import { MDXProvider } from "@mdx-js/react";
import Highlight, { defaultProps } from "prism-react-renderer";
import Prism from "prism-react-renderer/prism";
import theme from "prism-react-renderer/themes/nightOwl";
import "./src/theme/scss/main.scss";

(typeof global !== "undefined" ? global : window).Prism = Prism;

require("prismjs/components/prism-kotlin");
require("prismjs/components/prism-csharp");
```

The `Highlight` component then uses the `defaultProps`:

```javascript
 <Highlight
        {...defaultProps}
        code={props.children.props.children.trim()}
        language={
          matches && matches.groups && matches.groups.lang
            ? matches.groups.lang
            : ""
        }
        theme={theme}
      >
```

Now I have beautiful C# and Kotlin code. Thank you again for creating this package 🙏

**Comment by jsjoeio** [comment]
Thank you @dan-auth0 for documenting how you got this working. I was able to get support for Rust :D

**Comment by jonnyasmar** [comment]
This should really be added somewhere in the docs or `prism-react-renderer` should provide a `loadLanguages` function like `prismjs`.

**Comment by jsjoeio** [comment]
> This should really be added somewhere in the docs or `prism-react-renderer` should provide a `loadLanguages` function like `prismjs`.

@jonnyasmar Totally agree! I bet you could submit a PR

**Comment by aamnah** [comment]
Worked for me as well, thanks. Please note that you will also have to install the `prismjs` package for additional language support to work

```bash
npm i prismjs
```

**Comment by travisdahl** [comment]
> This should really be added somewhere in the docs or `prism-react-renderer` should provide a `loadLanguages` function like `prismjs`.

if that would mean getting rid of the `(typeof global !== "undefined" ? global : window).Prism = Prism;` I completely agree. I need different languages but I dont want to add this global var. 

If there was a load function, maybe the package just gets rid of the out of the box languages and let users only include what they need? I dunno just spitballing

**Comment by hirenoble** [comment]
I'm getting below error when I tried this approach :/

TypeError: Cannot set properties of undefined (setting 'triple-quoted-string')

**Comment by vitalyliber** [comment]
@koxu1996 thank you! It works with the App Router of Next.js.
