### ISSUE TITLE
gatsby-plugin-mdx support?

### ISSUE THREAD

**Issue by satvikpendem** [FormidableLabs/prism-react-renderer#54]
I'm using gatsby-plugin-mdx with Gatsby and I'm also using gatsby-remark-prismjs for the code highlighting. I've seen it said that prism-react-renderer is more preferred than the remark plugin. If so, how can I use this? Because it's mdx, I don't know ahead of time what language the code would be in, but I'm most interested in dynamically changing the theme of the code on button click, such as on the [PrismJS website](https://prismjs.com/).

**Comment by huy-nguyen** [comment]
@satvikpendem This is what I did. 
First, create a file `CodeBlock.js` with the content below (taken from [here](https://mdxjs.com/guides/syntax-highlighting#all-together)):
```js
import React from "react";
import Highlight, { defaultProps } from "prism-react-renderer";

const CodeBlock = ({ children, className }) => {
  const language = className ? className.replace(/language-/, "") : "";

  return (
    <Highlight
      {...defaultProps}
      code={children}
      language={language}
    >
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <pre className={className} style={{ ...style, padding: "20px" }}>
          {tokens.map((line, i) => (
            <div key={i} {...getLineProps({ line, key: i })}>
              {line.map((token, key) => (
                <span key={key} {...getTokenProps({ token, key })} />
              ))}
            </div>
          ))}
        </pre>
      )}
    </Highlight>
  );
};

export default CodeBlock;
```
then in your layout file:
```js
import { MDXProvider } from "@mdx-js/react";
const components = {
  code: CodeBlock,
};
const Layout = () => {
  <MDXProvider components={components}>{children}</MDXProvider>
}
```
You can then remove the gatsby prismjs plugin.
