### ISSUE TITLE
Typescript error with import Prism from 'prism-react-renderer/prism';

### ISSUE THREAD

**Issue by saulpalv** [FormidableLabs/prism-react-renderer#84]
Want to add java language following, but can't compile

```
import Prism from 'prism-react-renderer/prism';
(typeof global !== 'undefined' ? global : window).Prism = Prism;
require("prismjs/components/prism-java");
```

Could not find a declaration file for module 'prism-react-renderer/prism'. 'c:/Users/saula/ideaProjects/Javali/client/node_modules/prism-react-renderer/prism/index.cjs.js' implicitly has an 'any' type.ts(7016)

![image](https://user-images.githubusercontent.com/19735362/83952898-81869e80-a7f9-11ea-851b-05a72d8a1cd0.png)

**Comment by swalker326** [comment]
What was the fix here? Sorry to comment on such an old issue, but I'm running into this now.
