### ISSUE TITLE
About included languages ?

### ISSUE THREAD

**Issue by soykje** [FormidableLabs/prism-react-renderer#85]
Hello,

First, thank you for this great work! :clap:

I'm getting started on a SSG NextJS project, and I was wondering what was the purpose of the limitation of included languages? I guess this is about bundle size and performances, but what about just using something like the `babel-plugin-prismjs`, instead of the method described [here](https://github.com/FormidableLabs/prism-react-renderer#faq)?

I'll be happy to discuss that!

Thx again

**Comment by jeffzh4ng** [comment]
Hi there, I'm trying to include syntax highlighting for Rust in my markdown files but Rust is not part of the included languages. Any idea of how I can add syntax highlighting for Rust?

**Comment by soykje** [comment]
@jeffzh4ng Hi, Rust language is included in PrismJS,  but the bundled version of **prism-react-renderer** does not include all of them. You can follow the guidelines from [FAQ](https://github.com/FormidableLabs/prism-react-renderer#faq) to add support, or install the `babel-plugin-prismjs` package (like I did) and then declare your specific languages directly in the Babel config file (see [here](https://www.npmjs.com/package/babel-plugin-prismjs) for more details).

**Comment by jeffzh4ng** [comment]
@soykje Thanks for the response. I'm not experienced with Gatsby or Prism at all. Where would I place that code snippet that the [FAQ](https://github.com/FormidableLabs/prism-react-renderer#faq) is telling me to do?

**Comment by kitten** [comment]
@jeffzh4ng you'll have to pass `Prism` (the default export from `prismjs`) to the `Prism` prop of this library.

Then either you make a file that just reexports `Prism` to add Prism manually to the highlighter and import all the highlighters you need or you can use the linked Babel plugin instead and won't need your own file.

**Comment by jeffzh4ng** [comment]
Got it, thank you 🙏
