### ISSUE TITLE
Fix plain tokens not respecting cascading styles

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/prism-react-renderer#9]
Previously I incorrectly assumed that if a plain string token is nested inside other tokens, that the plain string should still be styled as `plain`.

(Not sure why I thought that...)

The correct behaviour if a plain string is encountered inside a `tag` for instance is to style it as a `tag`.

See: https://github.com/pomber/code-surfer/issues/12

**Comment by SaraVieira** [comment]
Example JSX: https://codesandbox.io/s/jl8jx3zlqy
Example HTML: https://codesandbox.io/s/4z9pojvn60
