### ISSUE TITLE
Weird border styling at the bottom of pre code blocks?

### ISSUE THREAD

**Issue by tr1s** [FormidableLabs/prism-react-renderer#92]
10% of the time it doesn't show up.. but most of the time it does. I don't know what it is. I don't see any before or after elements. I don't see any hidden styles. How do I get rid of this?

![CleanShot 2020-10-05 at 15 05 19@2x](https://user-images.githubusercontent.com/19172250/95121516-2324ea80-071d-11eb-8dff-b56237de5474.png)

**Comment by kitten** [comment]
It looks like you'll just have to add some `overflow-x` styling, like `overflow-x: auto`

**Comment by tr1s** [comment]
> It looks like you'll just have to add some `overflow-x` styling, like `overflow-x: auto`

Ahhhh yes. It was a scroll border, lol didn't think of that. Thank you!
