### ISSUE TITLE
Is this project actively maintained anymore?

### ISSUE THREAD

**Issue by bendtherules** [FormidableLabs/prism-react-renderer#93]
Is this project actively maintained anymore? The badge on README says so, but from the activity - doesn't feel like that.

**Comment by kitten** [comment]
It is but I'd consider it more "stable" now. Due to the utility nature of this library I wouldn't expect it to change often since it does serve its purpose.

I still have to go through a batch of issues to make sure that it's indeed fine as is, as I would every now and then. But what you can expect is that it'll remain broadly the same and will likely just receive Prism updates over time since it has a vendored version of it.

**Comment by bendtherules** [comment]
Got it. Few comments in that case -

1. The components in this library don't seem to be actually concerned with the rendering part of the code snippet. It parses and provided utilities which the children uses to render.

  Given that, wouldn't it make a lot of sense to change Highlight component to a hook instead, like useHighlight?

(even if this change is not done, the Highlight component should IMO, try to render the children as a actual component, not call it as a function. Opened another issue for this.) 

2. There are many files untouched since years and are not formatted properly with prettier (after prettier was added, no changes in those files). Makes sense to do a batch fix?

**Comment by kitten** [comment]
That's an excellent idea! I'll carve out some time for that 👍

**Comment by bendtherules** [comment]
Added a hooks version in my fork - https://github.com/bendtherules/prism-react-renderer#using-hooks. 

I will be happy to open a PR.

**Comment by kitten** [comment]
Sounds good! I'll happily merge that. Cheers! 🙏

**Comment by AlfonzAlfonz** [comment]
@bendtherules Could please submit the PR? I'd like to use this in my project :)

**Comment by bendtherules** [comment]
@AlfonzAlfonz In the meantime, you can directly use my fork published on npm - @bendtherules/prism-react-renderer. 
Will try to raise the PR soonish - it'll be even better if you can take a look at my fork (https://github.com/bendtherules/prism-react-renderer) and extract just the hook changes into a PR?
