### ISSUE TITLE
The none language for disabling syntax highlighting isn't works.

### ISSUE THREAD

**Issue by eliooses-zondax** [FormidableLabs/prism-react-renderer#99]
Hi there!, I have followed all the instructions of the `README.md` file of the Gatbsy plugin `gatsby-remark-table-of-contents`, but I have the following problem in a Gatsby Carbon Theme project:

The following snippet:

![image](https://user-images.githubusercontent.com/74009760/100834288-66b08200-344a-11eb-8247-4ddfb5da0b4a.png)

Into a Gatsby Carbon Theme project render like this way (a Gatsby Carbon Theme `pre` code block):

![image](https://user-images.githubusercontent.com/74009760/100834318-7334da80-344a-11eb-986f-29b641f55118.png)

![image](https://user-images.githubusercontent.com/74009760/100834446-ad05e100-344a-11eb-9e2a-4e05e391f53c.png)

This is because the Carbon remarker overrides the block above the directive of this `gatsby-remark-table-of-contents` plugin. I have tried different commands and settings in the `gatsby-config.js` file but all to no avail.

Reading, I find that Carbon Theme uses `prism-react-renderer`, and that they have prepared a language "none" to avoid highlighting, I have tried with that and even so the conversion to the code block is not avoided.

I would like to know how I can avoid this and in turn add "toc" as one of the languages to exclude.

I understand that many starterts and themes must go through the same situation, so I believe that a solution must be found. My knowledge is limited but I can help by testing a solution/workaround that comes to mind since I need to solve this in some way in the short term. Thank you in advance.

**Comment by kitten** [comment]
Hiya, this works as intended and is the minimum rendering in prism-react-renderer.

You probably want to open an issue or check that Gatsby theme you're mentioning as it's up to that to alter the rendering of code blocks
